---

- name: Create deploy-user on the machines
  become: true
  ansible.builtin.user:
    name: deploy-user
    shell: /bin/bash
    create_home: true

- name: Make deploy-user a passwordless sudoer
  become: true
  ansible.builtin.copy:
    src: deploy-user_sudoer
    dest: /etc/sudoers.d/deploy-user
    mode: '0644'

- name: Add deployment SSH key to authorized keys
  become: true
  ansible.posix.authorized_key:
    user: deploy-user
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
